---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }}"
  cluster-cidr: "{{ cluster_cidr }}"
  service-cidr: "{{ service_cidr }}"
  disable:
    - coredns
    - flannel
    - local-storage
    - metrics-server
    - servicelb
    - traefik
  disable-cloud-controller: true
  disable-kube-proxy: true # Cilium uses eBPF
  disable-network-policy: true
  docker: false
  embedded-registry: true
  etcd-expose-metrics: true
  # This needs to be in quotes
  flannel-backend: "none" # yamllint disable-line rule:quoted-strings
  write-kubeconfig-mode: "644"
  secrets-encryption: true
  tls-san:
    - "{{ kube_vip_addr }}"

  etcd-arg:
    - quota-backend-bytes=2147483648
    - auto-compaction-mode=periodic
    - auto-compaction-retention=1h
    - snapshot-count=10000
  kube-apiserver-arg:
    - anonymous-auth=true
    - watch-cache-sizes=events#0
    - event-ttl=1h
    - max-requests-inflight=200
    - max-mutating-requests-inflight=100
  kube-controller-manager-arg:
    - bind-address=0.0.0.0
    - kube-api-qps=20
    - kube-api-burst=30
  kube-scheduler-arg:
    - bind-address=0.0.0.0
    - kube-api-qps=10
    - kube-api-burst=20

# kubeconfig
retrieve_kubeconfig_server_address: "{{ k3s_registration_address | default(kube_vip_addr) }}"
retrieve_kubeconfig_local_path: "{{ playbook_dir }}/../../kubeconfig"
