---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }}"
  cluster-cidr: "{{ cluster_cidr }}"
  service-cidr: "{{ service_cidr }}"
  disable:
    - coredns
    - flannel
    - local-storage
    - metrics-server
    - servicelb
    - traefik
  disable-cloud-controller: true
  disable-kube-proxy: true # Cilium uses eBPF
  disable-network-policy: true
  docker: false
  embedded-registry: true
  etcd-expose-metrics: true # Required to monitor etcd with kube-prometheus-stack
  # This needs to be in quotes
  flannel-backend: "none" # yamllint disable-line rule:quoted-strings
  write-kubeconfig-mode: "644"
  secrets-encryption: true
  tls-san:
    - "{{ kube_vip_addr }}"

  kube-apiserver-arg:
    - anonymous-auth=true # Required for HAProxy health-checks
  kube-controller-manager-arg:
    - bind-address=0.0.0.0 # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-scheduler-arg:
    - bind-address=0.0.0.0 # Required to monitor kube-scheduler with kube-prometheus-stack
