---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets:
        - atlas-nl.rya-tone.ts.net:9100
        - atlas-ru.rya-tone.ts.net:9100
        - keenetic-fm.rya-tone.ts.net:9100
        - keenetic-hm.rya-tone.ts.net:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name wg-easy
spec:
  staticConfigs:
    - targets:
        - atlas-nl.rya-tone.ts.net:51821
        - atlas-ru.rya-tone.ts.net:51821
  scrapeInterval: 30s
  metricsPath: /metrics/prometheus
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
