---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file:
          - bootstrap/**/*
area/devenv:
  - changed-files:
      - any-glob-to-any-file:
          - devenv.*
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
area/k3s:
  - changed-files:
      - any-glob-to-any-file:
          - k3s/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/**/*
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovate/**/*
          - .renovaterc.json5
area/scripts:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - .taskfiles/**/*
          - Taskfile.yaml
