---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rockpi-poe-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      rockpi-poe-controller:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/tolkonepiu/rockpi-poe-controller
              tag: v0.3.1
            env:
              - name: POE_LV0
                value: "40"
              - name: POE_LV1
                value: "45"
              - name: POE_LV2
                value: "50"
              - name: POE_LV3
                value: "55"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi
    defaultPodOptions:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm64
    persistence:
      proc:
        type: hostPath
        hostPath: /proc
        hostPathType: Directory
        globalMounts:
          - path: /proc
            readOnly: true
      thermal:
        type: hostPath
        hostPath: /sys/class/thermal
        hostPathType: Directory
        globalMounts:
          - path: /sys/class/thermal
            readOnly: true
      pwm:
        type: hostPath
        hostPath: /sys/class/pwm
        hostPathType: Directory
        globalMounts:
          - path: /sys/class/pwm
            readOnly: false
      gpiochip4:
        type: hostPath
        hostPath: /dev/gpiochip4
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/gpiochip4
            readOnly: false
