apiVersion: v1
kind: Secret
metadata:
    name: ironclaw-secret
stringData:
    IRONCLAW_DBNAME: ENC[AES256_GCM,data:3zfcxtqfBkw=,iv:MkZeK9jO/zR1I/xvYRtO99G4+bZ/t7Z8kC2IPv70XE4=,tag:KNpL/PEqOqaIojRifxESlA==,type:str]
    IRONCLAW_DB_USER: ENC[AES256_GCM,data:PI7CORbZSAU=,iv:RH4+CS5dx6Kh4fNNZ1jOYU2KLn+IhE29RxiQolTxY0E=,tag:9ALNm0l2OT6xVIe9bXDWmw==,type:str]
    IRONCLAW_DB_PASS: ENC[AES256_GCM,data:IHkU7UoK65yO2S1U,iv:surG/6GHkhOPoyYnpo1jXCqTUXB9w/YXPoi+Y8rZpwg=,tag:geVhdmNME0akk/BmueFaXw==,type:str]
    HTTP_WEBHOOK_SECRET: ENC[AES256_GCM,data:Q3q0cof6Rq+Qbq3F0cNSs8/fXRkix/YKM0KYzE6+Mh0=,iv:i+uEDwgge8eGuknZ6nXvTbO64rkqBnCT5UEaguD09TA=,tag:xTUkjZNzQrmZoq5wH9amCg==,type:str]
    GATEWAY_AUTH_TOKEN: ENC[AES256_GCM,data:ypimODjgks0x4K2sqnC7OdOoI7IqBSvsygwl7v3EXkc=,iv:qSSZRW4RjVTx+QSkFMpBcNWKY8U2rrQnt2ct/SfWDnE=,tag:eCiWx63mSF5soedHuHKXBA==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2gxeDg0cVNKQXQvMkc2
            NmdLbEpwNWJscmsrYVV5c1M1MDUrMjdvcWhJCmJOZmcyQitGRzVjYjJ2Vko0M3Zo
            UEZsVzJlbnJRb0JzdG81RlNLQWFpblEKLS0tIEdrNDVZSjF5SDBMYTd4VHVsU3ZF
            eWdXQU1FRlVWUk16SHhsdUdoS0UrL0kKSwWVHoWSUocCgWJvmEgKr2ucqh7xV7Rv
            Dddb42FSnhZdoW3J5eT2Ff0thWOI3za1/ShsTeIyk8yrATzT+T7DRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T14:16:07Z"
    mac: ENC[AES256_GCM,data:bQxGkSrhNPznboYRXK0f9L7qy1dDVzOVOfiVkywuMutjrUA1CD1nRnB+OxbqVKmyJpawnKpebZmg9QMHcU7vq70/9yL1TGS9SqfFPKcMkEFOpgyy9gIiOVgSjJrzolFUBQm8hVukX153Bxbp9bDtL3cPRbQ8mvvdhEk+ERmNRko=,iv:Jtig5RaZWNUpi/50NP6D9LfJXugTdciXEZgLcE2BR6Q=,tag:2Spdt1YDgb52JGHQ1ZkJbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
