# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:E6c4ZGtJXswnvevdffjcWSuNGErNOaGgpW1LyJLfDDekETAIVhfi0g==,iv:pCQv73xXH+6I3imJJXpw1CLe7ciNeu059gjobWa2eYA=,tag:FhQW8rMcHJJzMxkchqITxw==,type:str]
sops:
  age:
    - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR01sS3FpZHR3a000eWVE
        NjdUV1BlbkxVazIrWUluTksrZWVkLzFBMGtNCm1YRElLMU40cEZteFlxcWxMeU5N
        SGVyVDUrc2hqOUlWV3g1RVVJWjkwdGsKLS0tIGdFSEhpTHp0WUsyK0h6eWtGdkRK
        TmN0QktTeEFyTmRvUG5zcy93SGg1dEEK9UcmftGMKu3MPKSbBCom9+SOGxUIDLR/
        fy8cgLlVOo9me1lL1sa3eTJFY4aCVA6eR9HYnsssxFP3rFqmTLS6Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T07:55:12Z"
  mac: ENC[AES256_GCM,data:gqAIMax78uyft1PmuW42F6SBWC4o3Vm5+C0azlPbAIzdbcL/+sGp/y47pNneAmirQiTKAOW5Y9chXcSYORBknbU2FCiBNZfW4ww5jAXb1nhj2LUFlWw9gVpRigzLcGlE6FbN1fjyFX6jZb4htaOJce8XXB4Qyi+4/VR0eA6ITqY=,iv:21Dljj++M5UR4FXPhAB6zo2usClXNrYqsoWsiNrnh9c=,tag:CH6JPiPyoBXWf9b/e9rltQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
