---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
