# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:mL9fw1jbPvvgxW5hLgbAE0GOp4M7lVub+2n2hqgKqmif0wWgLx68bEdZgL/w4R2K4jFb7ZlJxc8O2kjxJTWRLEukHkThtIO7uTSbnCAlLsvQwMvre2amPg58tbpQBVV41gHC6Xwoa6e8d7HjCg8V+/LHWCbFjV320hhhvC4XGsSkOxHXojtjN8cWoWQ4Q0QUMT00Ol9Ml2o+w3jyHATV6CDrDyk=,iv:fVQ8THRwTps61vbTf3rqui/fDbhFHfdKWn6KjShGh3g=,tag:Cwv4njs49UHqTRufVp206A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:omAsEOukaD53UE7bUCDNiaskyVcaeSOQgXyM+zUkTIypFTUnns3GVnlviV+Mt2yCLD/sZch1buiMXcPUa6dhYqAfwsjoVTN6cA==,iv:FfTR00KhjBeCXUwbpUGM0+7UzEMsDLFUSOEdk1Scl10=,tag:1cSIcMj2Ec3NkNCxOEEPQA==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:v2VD4+Ejuh+Im1tgz+jQEFjP5momAhTULjhbJEcmTxMUdm1VEzKtexfvRRmXRSuYcDWT4tEr92C8VDSRHs43qA==,iv:A0QE7B3Ecb4s64iN5Jta1aU9x14YM6Et2nHyIIemnYY=,tag:DUPgDqL73mVLJ0r36gbEhQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:8ZxXcYrmO1D8cCTmtRPWr6KEmPcecDspa/fOu6gzHIRlJ+0F2LLViA==,iv:8GRnEg5Ujx6pADWriZn4l/gOS16QXiB+Ht3GjKBMYMg=,tag:+0PQOakbqaxU9V7jjY2Q/g==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:GO9IomF1HI+NiIpDYAzNx+WO94f5K57FI1dMR20ONXOLj+EvJsmWLylqzw==,iv:Wgp2z/rBvhW/2b2/nUoWKZ+f5i6xSQDczc8Vq3jbdMs=,tag:aN7jd8h5Fj/+YZRvhDdhKA==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T06:32:43Z"
    mac: ENC[AES256_GCM,data:Dw89b7Cm6FxBbKPgFZXZHJD7+IJYgayw6O36DA9BMNPuiBZez4MWEecfBiSJv/O9jVuR8kXvLulTl26RZAkq1FP/gn0/xAHZCnHfq7kcT6ynYd8jKLvaXSltLuh963t+ZKCHx9cRaLDjJ78fKclxyLGqTYvPh1PSA/R+kK2I7yM=,iv:UndKPwDPqNO0X+DB5Uegt+FrJNqbQ0TXxGvOyA8iuTQ=,tag:7kG/m4hdqab/KjNnfMwBcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
