# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-gateway-token
stringData:
    token: ENC[AES256_GCM,data:+HWGTgQABnqEzHS7BgfPWKrHEItfsXM39POKeZ0OREANOpDq1Fjd+2ku3fWAgn1huAjr/9fsCNExbQtR1eEGXw==,iv:haP3gworj8ymWpajhFbrQW8U78uSO+V27ngboH/cUt4=,tag:YRDipixCIuc5bzNuiVIm6Q==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T13:14:17Z"
    mac: ENC[AES256_GCM,data:+loYpQe4NDiSY3umnxqgILo0GmIFAf/c87DuwudnV/P6lEHCqm+hFrVv6gDn7ou5d6tBssYnNr4ujrFmCSWlQN4VLL1StFqg6uqsyVW5m3P0K4juMQnfR0+lqNVU1ZeerddnrNF92tT0JsZmACTACCSxo4UxuYATfT7wk6tXzl8=,iv:swsnF/MgEnrw0jvhxIf4e9Z3w8UqZfamHUqlvrwdg50=,tag:kUcU2EiWQlY3vPowSo8mcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:mL9fw1jbPvvgxW5hLgbAE0GOp4M7lVub+2n2hqgKqmif0wWgLx68bEdZgL/w4R2K4jFb7ZlJxc8O2kjxJTWRLEukHkThtIO7uTSbnCAlLsvQwMvre2amPg58tbpQBVV41gHC6Xwoa6e8d7HjCg8V+/LHWCbFjV320hhhvC4XGsSkOxHXojtjN8cWoWQ4Q0QUMT00Ol9Ml2o+w3jyHATV6CDrDyk=,iv:fVQ8THRwTps61vbTf3rqui/fDbhFHfdKWn6KjShGh3g=,tag:Cwv4njs49UHqTRufVp206A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:omAsEOukaD53UE7bUCDNiaskyVcaeSOQgXyM+zUkTIypFTUnns3GVnlviV+Mt2yCLD/sZch1buiMXcPUa6dhYqAfwsjoVTN6cA==,iv:FfTR00KhjBeCXUwbpUGM0+7UzEMsDLFUSOEdk1Scl10=,tag:1cSIcMj2Ec3NkNCxOEEPQA==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:GO9IomF1HI+NiIpDYAzNx+WO94f5K57FI1dMR20ONXOLj+EvJsmWLylqzw==,iv:Wgp2z/rBvhW/2b2/nUoWKZ+f5i6xSQDczc8Vq3jbdMs=,tag:aN7jd8h5Fj/+YZRvhDdhKA==,type:str]
    HINDSIGHT_EMBED_API_URL: ENC[AES256_GCM,data:GVPzGygWkmjl05Lj0fm6+y5F0KCcJOBpuZmPfMrFGPeGCA==,iv:eOC4cVPbbRdXXlSx01uhgXCsBBwQf51q13Pje1M2Q1k=,tag:11Lwd3E+86JJsmYpAFBXPw==,type:str]
    HINDSIGHT_EMBED_API_TOKEN: ENC[AES256_GCM,data:Z4BQWOOYUn9YBY2Iky/BV6EOJMA2IBeZdzst6F39lBwrNWzXa8ymLOPvfNtRV0riYTYD9jE=,iv:6wLs4lr8pihfCRpiKWNafQOHtlyyXvNQfcyZJc6RlGI=,tag:paaZY740uesFTijHdZeJsQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:vdJrCn0n5oPy2PfHpeZWUfqZscudyRqb+dCEk/r28vQUgi9qNmRusw==,iv:8ap5GOEr73DDmGJMhdQXQJYS4bpAod0lGxDSTGInBLw=,tag:ST33uVKTM9heKLhUzJ/6Dg==,type:str]
    OPENCLAW_MEM0_DBNAME: ENC[AES256_GCM,data:k75K/w==,iv:l24lP/7ULum2XBpzEnAZN/aglfPss5tljbT9sqzNihw=,tag:IaA9Phn7DbQoIhbDA6kg0w==,type:str]
    OPENCLAW_MEM0_DB_USER: ENC[AES256_GCM,data:0Pvkbg==,iv:UwPxCaA45MzkCu/W5KSyXzZymi6JmNcP56m98swQaMg=,tag:qTxudPbeh/8thdD/XRzR2Q==,type:str]
    OPENCLAW_MEM0_DB_PASS: ENC[AES256_GCM,data:k+xoVaf4oM19ygM/,iv:eGof1MUmewMah4+0cDtPZcU6UJOyCKkAnjEhKtjVDw0=,tag:rjZZMzXeaE5gflqwKsuplA==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T13:14:17Z"
    mac: ENC[AES256_GCM,data:+loYpQe4NDiSY3umnxqgILo0GmIFAf/c87DuwudnV/P6lEHCqm+hFrVv6gDn7ou5d6tBssYnNr4ujrFmCSWlQN4VLL1StFqg6uqsyVW5m3P0K4juMQnfR0+lqNVU1ZeerddnrNF92tT0JsZmACTACCSxo4UxuYATfT7wk6tXzl8=,iv:swsnF/MgEnrw0jvhxIf4e9Z3w8UqZfamHUqlvrwdg50=,tag:kUcU2EiWQlY3vPowSo8mcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
