# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-gateway-token
stringData:
    token: ENC[AES256_GCM,data:+HWGTgQABnqEzHS7BgfPWKrHEItfsXM39POKeZ0OREANOpDq1Fjd+2ku3fWAgn1huAjr/9fsCNExbQtR1eEGXw==,iv:haP3gworj8ymWpajhFbrQW8U78uSO+V27ngboH/cUt4=,tag:YRDipixCIuc5bzNuiVIm6Q==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T14:04:01Z"
    mac: ENC[AES256_GCM,data:/BWYXq5id5X5SnnUSBK1J01G1XWSngEV9v2mf1MJv2SSEGhdHLQ6EHibAnWlLNoIoaiaKkibeG2A5XuUFSGkroQr500C5wCuo2nMGk/ANyQ+rTNV8y8EBUORkgGDa2LV2ZnWv+DYuR3Vdp5F9TO30pvEdM5lmm0TqIq+utzEMU8=,iv:maJVwYtlHf05BgU52kgNhbgGbEZmPLGyFtdfuqzNFbk=,tag:G2Wr1/aR5+SPemXbnXuIZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:mL9fw1jbPvvgxW5hLgbAE0GOp4M7lVub+2n2hqgKqmif0wWgLx68bEdZgL/w4R2K4jFb7ZlJxc8O2kjxJTWRLEukHkThtIO7uTSbnCAlLsvQwMvre2amPg58tbpQBVV41gHC6Xwoa6e8d7HjCg8V+/LHWCbFjV320hhhvC4XGsSkOxHXojtjN8cWoWQ4Q0QUMT00Ol9Ml2o+w3jyHATV6CDrDyk=,iv:fVQ8THRwTps61vbTf3rqui/fDbhFHfdKWn6KjShGh3g=,tag:Cwv4njs49UHqTRufVp206A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:omAsEOukaD53UE7bUCDNiaskyVcaeSOQgXyM+zUkTIypFTUnns3GVnlviV+Mt2yCLD/sZch1buiMXcPUa6dhYqAfwsjoVTN6cA==,iv:FfTR00KhjBeCXUwbpUGM0+7UzEMsDLFUSOEdk1Scl10=,tag:1cSIcMj2Ec3NkNCxOEEPQA==,type:str]
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:GO9IomF1HI+NiIpDYAzNx+WO94f5K57FI1dMR20ONXOLj+EvJsmWLylqzw==,iv:Wgp2z/rBvhW/2b2/nUoWKZ+f5i6xSQDczc8Vq3jbdMs=,tag:aN7jd8h5Fj/+YZRvhDdhKA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:vdJrCn0n5oPy2PfHpeZWUfqZscudyRqb+dCEk/r28vQUgi9qNmRusw==,iv:8ap5GOEr73DDmGJMhdQXQJYS4bpAod0lGxDSTGInBLw=,tag:ST33uVKTM9heKLhUzJ/6Dg==,type:str]
    #ENC[AES256_GCM,data:u2jYnEKZFA3QII+heP44HptdXbAfzDb4F+REWors3NwjEubI7ThleWFKqIvr7RAKGmH0hlheNZN+LBEPCFyvvHfxcdMDUWO4S4U9h3b2UaedfrIxgwo9hw==,iv:e1c2Q7fQV+ZJd6A2mreYaXr7omy9fThseQtTmEFX3mM=,tag:JDLJvmf/gGbuyBSUASmt+Q==,type:comment]
    PUSHOVER_APP_TOKEN: ENC[AES256_GCM,data:Ex99k1DPZFDExKkCoRNjlq/EDh9Itdxebei+ZRij,iv:dPlW+GDiN6DYlPUZZFS3B1d3zJ8DHP566gC0e4yCzbc=,tag:wAG1Wz/iRHGqJJJH38iDcA==,type:str]
    EXA_API_KEY: ENC[AES256_GCM,data:XYcU7GcJ8L4TZ/mH+FQi/t8TvgS4a+pN6HVNDGNzICCUqw/m,iv:2E08xDOeWagtv9qjSWXEUyjkHwdNKw6hcqjEYFExhLE=,tag:pUh3cuGMnhyYJB6JjIcKFg==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T14:04:01Z"
    mac: ENC[AES256_GCM,data:/BWYXq5id5X5SnnUSBK1J01G1XWSngEV9v2mf1MJv2SSEGhdHLQ6EHibAnWlLNoIoaiaKkibeG2A5XuUFSGkroQr500C5wCuo2nMGk/ANyQ+rTNV8y8EBUORkgGDa2LV2ZnWv+DYuR3Vdp5F9TO30pvEdM5lmm0TqIq+utzEMU8=,iv:maJVwYtlHf05BgU52kgNhbgGbEZmPLGyFtdfuqzNFbk=,tag:G2Wr1/aR5+SPemXbnXuIZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
