# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dPShjkARISa9G46o8QlpXaSuMt0B4TZUoXOfIk04yvM=,iv:FwSO8rdy7teVk2iTpBf5o4bg9G4pLSp9hUxf++dtGjw=,tag:TvanNea8i6i9K1wLcP00FA==,type:str]
sops:
  age:
    - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc05vanZ3TmdVakliOFMr
        OEtrYVJNQUNkNXR0bWE0TXNlOER6ekJJbVZrCnk4bHZHVUR0U0tmWGxaVCtXNWth
        UDIySVJZY3cyU1FlQ0FxR2d2THdzMXcKLS0tIE04ZjQzd2Z2SERuUUp1eWh4MVd4
        dnA3aTRXb245MzZHZk9tZDAxRzFUdGsK93bOZ3VxGtSkAKEl3vduhY661/YdWkY0
        3uja4WS7NfvSoiz90XBN7RU0dlCcL0LRlgnwegDUATKWhkqbyvqleQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T07:55:12Z"
  mac: ENC[AES256_GCM,data:9cak01P0i6VCF+eK6yipDPFh8gjCMrLGFQQSRWX6bQ4xoYVsfYTXk0tPbUnrqxY1smuwR+W2ph7tRhLuxcdU3vFqmxqUtpkil5bRQ6VLH2HEbisJUVNVaH+iUFNbtoQ+F+rielWHw7pO2H50FYSx+0ani0hh7xJZpReVBsWS5Es=,iv:38mTRx+4fD0jIIIWAwwJ2no4gR274WGSY8FSzMKz7zM=,tag:ycvXqjXVIjo1tXsm+S0eqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
