# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:C4S7Hq+iggy3dJd6ncKiSlQvnW52l9ZhWqTsG6ZFEOa7vTLP4dHrdBDwHaSIb2FLVBjHHYX6fOlBMgxW6sewmjcc1LyngeT9VCaj9dYuqSVt7mD3/lC1fHOZKws0Hz/cWqICmyENijl8lVBR59BLBwBazjEAPrDODJJE2OeGj5HUghx4VbmRqyqU78hsfyqc2AYMqNZH3abbFzK6CNtqO0HsW6S4hFh/NtY4CQBqhYt2hJfZ,iv:Ob433uwgLIKTeWOo7i4KgKS3Lfkybw1gQgreTp6iDEE=,tag:fbQXvMk7JY0DHq4QNx83zg==,type:str]
sops:
  age:
    - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMlN6d0F1bnNzWXNIdElY
        b0VLL0JaTXd3a2l0QS9ZZFBIU3c1azYza2xnCjhzUUxWR05sWXordGdQejF1aEVv
        N0lkYTJPN2pYS1dWMUdTUHNrdW03R3cKLS0tIDZibWRkWjBxdkRRZFd4TlJoTlRl
        OE5SbSs1eEdoZHlmNXRIdnIrb2hTSjAK2j4H02gPwwUKHLNZEs+7k3sLiCGGDR1C
        XopdbajCLEXT24Ka7guO92tgSEnMeckbA0bwFIy02IDvonRLPRysUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T07:55:13Z"
  mac: ENC[AES256_GCM,data:kvXgkK277Em3tuB42d8r9fKzr6v01X1obxNjiJhm2I9QPdahvKAtDwEFuRdRxOKjmIsIv0z9+uv0cnKsfXwmnkiyfEyV1fogfZjcPwEa1N7hk/x4tYTQqWsKebQOFLq7QhlWewlIp5sttUIg11nzeTjcn6HqZapONSHiDfJYZVc=,iv:bZmTw4MeVEkgCUy8kxheLBwkBXbcKOZRuk/CPCLnCW0=,tag:tVlulC1+x2vYqxf5Hv6nZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
