---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Retrieve kubeconfig from k3s cluster
  hosts: controller[0]
  become: true
  gather_facts: false
  roles:
    - role: retrieve_kubeconfig
