# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:biGj8UB/sITU5yh0w+0sPgWHWVbZMV8L6QQkqV20OBA+dPuuVr8WxQ==,iv:kH0MZ0sJQWy6ZItIFCy6C9lcy/QyjCsTUjP+TGPNoAM=,tag:iroRl5KsCG6FSvy1RiGJWg==,type:str]
sops:
  age:
    - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y1dhNCsvZ1IrcWd2UWlX
        LytSbm56cVE0TENhV0VvR3kyOStHL3JZc1VzCnd0d1JpNkw4ZEh6MFdIOGR3RUU3
        aHZNcW5kSUxxSjdnV25aNm5tRnhIK0UKLS0tIFdHL3dyaStyNG9qRVU0OUt0Sllx
        WGRDYVQ4OTNRRUxRNzhHdWtkd1E0RVEKf9VP6ZQ0eXSlLZXXLVUWdLKE316UWh7Y
        GlCbz61xOC23ykKEMmuHSWgimhElN7e1j2L90DuH9McI+/6AIB4w2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T07:55:12Z"
  mac: ENC[AES256_GCM,data:tXP8zyr0kyGKWb2nH6Z/4XyYZia+0iqxFsWbIbPj/WXTR5E1ipL768lrT7rRFIOZB17foeGrxKmB0JOIBuqGMu00EFqKFpJYHFxte3UscRALmhtWfHIGj4kvNDYoFaW1A2WgTaBRbnzgvrERYrcB+Y01lRF3cEci+OYkA4UTYDQ=,iv:2gE0MPG/5ZaC1tqY4v1WkoYtjRyj2xrwH+Z6falFmSw=,tag:ajNzCEJYGd3MLZ7YHrGJ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
