apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-config
    namespace: default
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:vhXZlolY80UTTgq4ErQqp3NqyQW1YYK2H8rV0zn0ROwUneW7FVaWmnhTLOUTW+NhSnB9yxY6uuH8YbcQGoDd+B++wDoZeRVLLOZCulVniGqweXEuqtXzzM4DrAIBodie9S5FBPyVSepTTPL2YzdLH/TrG69x1xMF8KpM8UkyQGN1P6+g1SaJQqZPwLprHenaMVXN9sTKSB4aF6p17r3V3FKj2l6ZVQihz0+l+aniceNGwEooiaE/cIwm0J0EpecSEAw+Dk+zP6C1s1LoPUS/QT8LRcRBarT1HHOE3W6HUUBJpfZmfDqyHkiK84fdthlEpcb/NY7vXoIsZZvWL5VokbuU0+JiQ+l5bAqsqCDF801RMqiIPqqdK5Yu/uvknwGzc5CN35volX0N+OR2xC+WK8krq02H1j2VnNaWKUW+vjYzi6aRSgFnYNg0GfbF5Ksl14RsYMGa1PCE9ztcNu/mxElsIipXM65AepS3d/gurr3j+CO+g4olO8ujkLxJRiRWH0huM3Vs3Nb/i7tptHDYtdh27b+qq3WxQqhz97P9Xp6wmbcauav1s9kCPFPKQmzeNOICU809P8zvxECmB8etbS+fNeKOf7D7CFdNSXhGZ6NeiOLX8Xo9xah6WsKrOJ1x/74vG7kUksZShdK6emwCDo0+g8LadxSE+6cU4VntTHg=,iv:lbm+jsRkec10gk0tcPR/n/uczNH7/4l9vy08AFVY530=,tag:vFuy5Zl9+MibNZViTUprwg==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVdkNW5rNVVWNVJyWjVv
            cDlUUk1scHBNdWVUUk9PZCtXUUpNczhmbGlnCmVoNFA3SzgzL1ozZDhCc0x2ajNV
            NnljM282TVZhSE1kNFQ0M0VudHdjcVEKLS0tIHUvZE91YnRaMXpHcVFTbklGNEpy
            c1ZoaDhyOWZUZjg1SGc4VnlsdnJuRUUKKhwujAmAg5Y5itKIV33wMogGdw6crs2H
            xzZ3eYM0T/JcnR6N2kEUf6U3IEX3gCUKHOyysBgYn1crZWQLHIr6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T02:16:54Z"
    mac: ENC[AES256_GCM,data:RZnSRM6VUwkR8ViZnrtiHdu4zS1iDWxdUI4jMJxv+MEIMbPUD6XsicuIK/2BME0ohGAXaWOFijS/JyQrS0UB7SE5GZmbI9mh2eDEYheobeezY+YbtYITiBB7mRtRP6FKn7xaMpYIZqqez/xPvYkZVjmv7hyP4gWA9mDfsFGWZJs=,iv:PCQveL7AgCa4fNX6P1d3RCNuN8iKiGkROTv+/6cyDNU=,tag:r5lkiDZNk1FxZgIYA6vRUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
