apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-config
    namespace: default
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:wtbNqccHL7zXGXEbHDEtfkfoa6oPWVuApu79Q4Cq6GlOM6AVdlvVjhQOuL07zuAy8LiaHC0aCBfoj2OK3zLLiY/L5gLqTxPq6UazF0FZ3mPhxj68JLEmirDlaKRbpYCtr3dEkVEiij8hKEsN0GULpU+S6+4JoUcqqqs/MGQKdXmbxEuemW+1YjDrweENd5Xf0D6gFOLDd6n4NbsM35xV0HntON5XGnrQ27gssZJeo/jxFB+LVhBaBkaCu1/4jiYbMvbCEg1ONQjw/UL3t+ZHVwEDX5S+MWHvz8LbIWSzoD5K6r6SFCu9cW5ykKDbmqNUaBSWnnlhS/64OqHo6MFVdUBhnRUDawhzJmS7dv/PcByLMkV+aiKaGSKm+LNxjvocjrFrNT/mrHCvCAhKRXsVLyMHjlr8YuA/N2NUrMfH/WndfX79IQV9Evb7ilL3XHqdkz6E0iu5MKGseHc7lvCBr77fBBYlO8um7WW/gytfnwfNUuRkXF+hPLE18qwYT0uXgvpdAj200sWD,iv:Vwjhj5ej7JR4vRE9hlsr3KEK/5B+R052DlAb9Bf0C5g=,tag:vUl7usxPEAPx7ZXkbGnXYw==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVdkNW5rNVVWNVJyWjVv
            cDlUUk1scHBNdWVUUk9PZCtXUUpNczhmbGlnCmVoNFA3SzgzL1ozZDhCc0x2ajNV
            NnljM282TVZhSE1kNFQ0M0VudHdjcVEKLS0tIHUvZE91YnRaMXpHcVFTbklGNEpy
            c1ZoaDhyOWZUZjg1SGc4VnlsdnJuRUUKKhwujAmAg5Y5itKIV33wMogGdw6crs2H
            xzZ3eYM0T/JcnR6N2kEUf6U3IEX3gCUKHOyysBgYn1crZWQLHIr6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T18:40:44Z"
    mac: ENC[AES256_GCM,data:SJFKxVnA0Kd5928ePl90Qw2vheY92vGAqJJJGly2paZV891Fyvn69VP16Juwrz963I4HMvNrM7LTar8cxYxaHCQBidFkhR/OfyO8tjcy+sjEY5n1w6QFJEyVd1qDBYd7Agy2AyR5Dw1aDb4budoMxtdIvCrCTdzDSwFFZ9yCNJA=,iv:9ykiKZyEEE5euAdxOrqtqCkVyi1FuhGQkY3s1VzOmbQ=,tag:mlcjsRy2iV6UtK2vhN9C6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
