---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./exporters
  - ./grafana/ks.yaml
  - ./victoria-metrics-operator/ks.yaml
  - ./kromgo/ks.yaml
  - ./kube-state-metrics/ks.yaml
