---
originRequest:
  originServerName: "external.popov.wtf"

ingress:
  - hostname: "popov.wtf"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.popov.wtf"
    service: *svc
  - service: http_status:404
