---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
components:
  - ../../components/common
resources:
  # - ./zeroclaw/ks.yaml
  - ./1mcp-agent/ks.yaml
  - ./flux-operator-mcp/ks.yaml
  - ./goclaw/ks.yaml
  - ./kubernetes-mcp-server/ks.yaml
  - ./victoriametrics-mcp-server/ks.yaml
