# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:7felfg==,iv:fen4H/nHG1wRZwdqOymJcAbtgsxke1SyVn5STzmhDp0=,tag:/XX8YeWCZ9g0lXsJb0LWcA==,type:str]
    password: ENC[AES256_GCM,data:1TgUVEutYmv817J/l6fVmg==,iv:2CYAp/le6UXENaw+YlOGVKhjrQPoPwZ0jFurSoeerkU=,tag:dWUv+Z0FlqVgE7KDyf/88Q==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y1dhNCsvZ1IrcWd2UWlX
            LytSbm56cVE0TENhV0VvR3kyOStHL3JZc1VzCnd0d1JpNkw4ZEh6MFdIOGR3RUU3
            aHZNcW5kSUxxSjdnV25aNm5tRnhIK0UKLS0tIFdHL3dyaStyNG9qRVU0OUt0Sllx
            WGRDYVQ4OTNRRUxRNzhHdWtkd1E0RVEKf9VP6ZQ0eXSlLZXXLVUWdLKE316UWh7Y
            GlCbz61xOC23ykKEMmuHSWgimhElN7e1j2L90DuH9McI+/6AIB4w2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T17:31:07Z"
    mac: ENC[AES256_GCM,data:IXbYbCID0p52+HEMpgVPjLFRAV9RCp0DG+G6LKMTQjeESauYDuCafNSUg1HY+PnR23KXWxP6A9w3aVykMnKSJ4Pe+v6tkVNljBI/Mof7p0zUnLt/8oj1ewpbBojMqToNCanXVsTyYAfH1/YES17HHzjiNe2RHFphbIMAqzanAzU=,iv:NG9SKeB1nIhdOY78nhUI/5FjPSdvUhtAKjTh1hL3Ftk=,tag:zyW7Qimvjb4eYeVWCo719A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
