# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: goclaw-secret
stringData:
    GOCLAW_OPENAI_API_KEY: ENC[AES256_GCM,data:zdvbM+ebwgQ/YZ82px/kUeeSq8ZuaKuCpCvsY2Z58rwqsCuwsVkZST/udp6YKKsMcFi/IojezThDJvIikstHrTcM/YOz4w1wvqUyK5LWLa1x811gLeV0JwdRQJaOFeyz8iGhmBXu1rCFs+v4/xxt672sj2ZNeddbcTC3wiEc16qg7aenQlMA2LtBfJNv3LRUjeKLdNnvUL4lZdWRmzSYt+HHFCs=,iv:8rdHChiB+8mCZasIvGiTDo7+yK6BRi6IeyPtdeV/ONc=,tag:+EQojsT0mihDKqgsFNz7Hg==,type:str]
    GOCLAW_OPENROUTER_API_KEY: ENC[AES256_GCM,data:Bedi4UefaKLXHMoS4VLOb0g5PQfWt+8UmBsKP80vhncM7PZCqblYK4Nq8GS2BuhC68hELSKuPpgF6nF4Pt1tLI8YxspMWhn+YQ==,iv:vIAVL9wQFprhEDAUOrHh1ZNJzimN9M+zDsd4utBY+Bw=,tag:LmGM+f2e2KwfJOK6898m4g==,type:str]
    GOCLAW_TELEGRAM_TOKEN: ENC[AES256_GCM,data:q0vMK08wx8h+fayIgKhoTxWIUx9PhCZOSdJjV7J4e+CaDCi3nHN1vJoH3uWyqQ==,iv:twa0Du4avgAEPPPVesBqfQVP3VjvyZ8k63UQtlkEFcM=,tag:ynX7yF0o+afbzuCqrPADNg==,type:str]
    ALLOW_FROM_TELEGRAM_USERNAME: ENC[AES256_GCM,data:yB0JC242k7JMvFbbpw==,iv:mGaHA705JfQOC6KKeaiC/b2idTIlCtssPSVvB6pGvS8=,tag:zDqjYvNucEMASuIkxMiZ2w==,type:str]
    GOCLAW_DBNAME: ENC[AES256_GCM,data:m5Gk6Nyz,iv:OOuxonOMESZoxZzOnbWOQIXXh+tJQRJLclBsSnzGpw8=,tag:EWsBlcmH/jR0E3b2/lM3sA==,type:str]
    GOCLAW_DB_USER: ENC[AES256_GCM,data:AKmgYsdd,iv:sa83nYamc+3qYirLaHmNNpMQ4cJCdetFEMPw9CgyRPY=,tag:se0eA8KN2btLobGyqx/aiw==,type:str]
    GOCLAW_DB_PASS: ENC[AES256_GCM,data:ALwbY7gTIuK34RNmwz5s3aXG3wnu4ExIfSNh31SLcQA=,iv:q6hOrG08E2HsLAHLO5aXp2EdbJnS88vA0EsOE/BWItY=,tag:kb1R6bqzdiJQkstC79Pvvg==,type:str]
    GOCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:d1mJu1whLc4BQZ7dozxAeBMSKYPNZuGwAJL0U0rAh6ndaaK+W1mtP+xcxg==,iv:a8tcihx04DtHz4P2iMhbtukd+TfFZmeTlj/nXxdA3RQ=,tag:+0Mhj9cz+MOjTTuegIAsmg==,type:str]
    GOCLAW_ENCRYPTION_KEY: ENC[AES256_GCM,data:HJvM2eBb3JLsU5NjYd9n1/LXw86V00op4d/LrSEw0QXnqyuS5XhhqZl+Oio=,iv:iq8GXi7b3giqtDBgP7cUJVtnr8B1sS7zhDi6RAX+qHI=,tag:Mf3zY7cnrqKyVU0KhZaV5g==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:biyZOL7PBribuqHqH5d/zPpvVL5cBup2WTXQJjsR,iv:9qw0i8ZX6AlDGaCQWU8in7EogO45lRuBezykoKQvbR4=,tag:wZLvDJeMcCbkum6z5su87A==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T12:07:55Z"
    mac: ENC[AES256_GCM,data:/mi4e6l47gD7N9Z1CISNrigkUZiEjxDz+72x36I+pKkzWVqleXv60eW3Ig/iU09ZmGvwsmfmVSImE5q9VJ/m+7ofxTZ5lfaBhTiWy8tnRjr0VZwyO13AgFrAaixcUE/pqfhMwSv+yx50vaNJvTPVaXxIcQhNA7ZtSjZQjH78ugQ=,iv:pUbeG8e4qngXyrg0AmSyCUJLYXfYtxf/fk9+QNtjvbE=,tag:ZOXkA+qRVm9Gi40nL+cDJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
