---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hardware
components:
  - ../../components/common
resources:
  - ./rockpi-23w-poe/ks.yaml
