---
apiVersion: v1
kind: Service
metadata:
  name: atlas-nl
  annotations:
    tailscale.com/tailnet-fqdn: atlas-nl.rya-tone.ts.net
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-ru
  annotations:
    tailscale.com/tailnet-fqdn: atlas-ru.rya-tone.ts.net
---
apiVersion: v1
kind: Service
metadata:
  name: keenetic-hm
  annotations:
    tailscale.com/tailnet-fqdn: keenetic-hm.rya-tone.ts.net
---
apiVersion: v1
kind: Service
metadata:
  name: keenetic-fm
  annotations:
    tailscale.com/tailnet-fqdn: keenetic-fm.rya-tone.ts.net
