apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
data:
    client_id: ENC[AES256_GCM,data:nlTCDI5qLAzWUX9QZfVxdFqNd/t96erpn2R3Jg==,iv:hrm/b0a3iVLsSogQUZRNKhaYO2sEvQHF2Opcaz/JPbI=,tag:OXD+1HxEGKe/sNe8ZL4btw==,type:str]
    client_secret: ENC[AES256_GCM,data:BtofH7NY7mgJfMFyhRAbrXtQRMzVebuGbAanF0Q8QKnjthLAUGpuDN3MBrxc1LtGX6sz2nyVgE3DCO1Lbo9n6WhwB5DwuchqAun0p5u9Pv1twn/8GB3cAg==,iv:anNQlJsAoQnbq86mezB/FIxoXAQMbS0/CKTyVRH9XU4=,tag:ydMtQOGICQUsE/rnP0HvOw==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckVQSGRDc3pvdHg3UHVu
            dC8vc0dtV0hKU29jTnJUYUhDMndSRWNSb0J3ClpST0VZQkVDNDJGa3RxT2R3Ynlo
            cjF0ZytMV1dQNWc1Zm13VzY4RjlZMGcKLS0tIFM1Zk5UOFJWOXJZY0ZIZGRMRlVT
            eVQzalBrU255RzdERGFkdXZJU0JnYjgKgS04M/hCQWzc7UBNC61XJeGMsX401s7J
            V+x0KkpNDc/70lRn+HFK2wpfcwXKs23qARecI7yZKuDajMwiWTM43Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T10:00:49Z"
    mac: ENC[AES256_GCM,data:sXDWf/RsKQXtLT+xQffB84TBqXzW903A8nXsjFwts+0QDL619fKdyWoTK42Arw58GF//yk0CLtyNQi4QQz4Br0XgEtvQ4DTruSHIz9BGywlQ1Ay0xVMTWsllDreDLYytLDAW2SOVHapYB0uTHFLdf+v0Xi/dPr0RIy3JVwVEQ8w=,iv:DyqZDCPwJ4hfxCw/1cpkbGWzxELO5HXOE51TqkU2WSc=,tag:FaxnvntjqcH9qKuLL5JsYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
