apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:N1eU1UVGOPXccDJHHxxuBPY=,iv:DUQx5BNZlIjy/ec4dqJsLaThyYIB5MEB2aI8gDu6yjs=,tag:fJk6dLAOdt3oReafthk/Mg==,type:str]
    client_secret: ENC[AES256_GCM,data:1mZv2tixyuHZ0IxbupHGGSSJz3j1rWknHw38rwzwBSDaIp/GZ/oyRmQv2OlsNjDq0Na01WTMbjWTh+CTfZHr,iv:cDMH6tU9o4pMpM5Bu39Bz2QGAcYHPCS0xuGe2oXFbwE=,tag:/yL9hAlgWMKkTQjOlQAA4Q==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckVQSGRDc3pvdHg3UHVu
            dC8vc0dtV0hKU29jTnJUYUhDMndSRWNSb0J3ClpST0VZQkVDNDJGa3RxT2R3Ynlo
            cjF0ZytMV1dQNWc1Zm13VzY4RjlZMGcKLS0tIFM1Zk5UOFJWOXJZY0ZIZGRMRlVT
            eVQzalBrU255RzdERGFkdXZJU0JnYjgKgS04M/hCQWzc7UBNC61XJeGMsX401s7J
            V+x0KkpNDc/70lRn+HFK2wpfcwXKs23qARecI7yZKuDajMwiWTM43Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T10:14:59Z"
    mac: ENC[AES256_GCM,data:YzAMo2HxrxnclzeU4USM/HZjjd6BJ6Ac7ODuMmV6G+WPxe9N9cZkvRi2xXEQ4edQwnYvgKNL60kgGzl85cCJ2m9Z5x+erXlGIjZglGIFZiyTqG6Yo87VEW3JlWO3rwbUzNmn5oNLcinArMkFm8Ac6j9C/OFaTT+pmZoZT+M51sY=,iv:Cqkxj5tb7cCLUEUwSIftJIKe8fwfvvv7sFg8gjQF8YU=,tag:3+dyy/EDtKgogAdPF0/qmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
