# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: umami-secret
stringData:
    UMAMI_DBNAME: ENC[AES256_GCM,data:SlHbrxs=,iv:a9GoYpA4Hg+ZTp4WhsYWYgV4SlH8nYzoVF4q39l4fCI=,tag:/DrHwCwjIh0Sd61cSKAv5w==,type:str]
    UMAMI_DB_USER: ENC[AES256_GCM,data:6yxt5ME=,iv:Q+PtgPZnk6BU7j64rvn4IdCA1NQHIeKlaZpOih8EzPc=,tag:GBIV7pKf68wkg+jLeARcIg==,type:str]
    UMAMI_DB_PASS: ENC[AES256_GCM,data:qfmTk0ErxTXj0A==,iv:GqfT9rJdrh7CyPvaW91mw7xS8NWf21tjCPwYkM1oN0s=,tag:kIXxs7mUG93WceQAxEOQkg==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:azNgJkxCZ1s=,iv:wSsO7vhWEvM7fP8MgmnuSckbs6lKWbJ4uhFmg/cMgBQ=,tag:kdrA9oizeQFFRA9KkOOjpg==,type:str]
    POSTGRES_SUPER_PASS: ""
    APP_SECRET: ENC[AES256_GCM,data:K4VsjOdq3/jr29aP3fsaLSghXgWDsKGOlX58iAT/bttG81pNmPxfVVM1TYE=,iv:7dp6Bkut5Z8EeJVypbCXNHWOKujAjOjxnq10M8M8LYk=,tag:MO0gJBU0WNIJm8vLqBHXdQ==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UDZiZjNDdFFvOTRQTHFW
            bTQyMTlVcEttdGlwcVVRaE1UaGtaQmU2emh3Ckh0OGtzN1A4Y2JkUTJCaHJKeVpm
            VVAva0ZLV2lLeUs2eVZHbWVpZkJISGsKLS0tIE9FTXlLNXJZWTBzd3ljeUpaMm5M
            eERoRVFHalFETzlQTDkvS0NuLy9oejQKdW/TE1cRFYSCHnogEq8E7jp9MzymcjIx
            5xGFBw1q4Aqr31/BenVHhvFMQntpiFKy8n+69vAG8tCkexNsddczgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T19:55:14Z"
    mac: ENC[AES256_GCM,data:Aqmh7QG5bIxFiQ4+RBPPQjs9ZFUgikvtm/dA2wkiKgKuDvTGSBVDU8bZEHxVZWDm8bqZak2krsnwI+e+P/dKNUOfZ0f5ERQNr0lMUdW95aPMEqQXXUADY+WdidYF56QLGo+NiapQ49fR7F7/JHgVZxD2+YJplFQl2QtMenTvzno=,iv:MII3bRLO7Dyy7VxNJ6bhd2EN3geyP9E7CSnJGjVqA40=,tag:APStoCCqloUdnJ9tmWQOPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
