# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
stringData:
    ATUIN_DBNAME: ENC[AES256_GCM,data:mLX55l0=,iv:XKZKHUF0/eoFmViPRhOWOVzev9jnmMLT8Aia2cAscX4=,tag:NnQ9xUVJQ+EC+QIJj8v2gw==,type:str]
    ATUIN_DB_USER: ENC[AES256_GCM,data:cZcZBbg=,iv:wd0WOS7rl3rWXbRcPEo4i33akmtpX7oXl5iBVoJhM4o=,tag:CQESFgmGEv57o2D4hOb4Ig==,type:str]
    ATUIN_DB_PASS: ENC[AES256_GCM,data:eTIdQYu3K2usVdrq,iv:iB6JzDPrn1xCiOCvhTMKH6HN6n3EsHQUGUgUbmAZguM=,tag:6rON9XYWAYgI2AOsTtyrWQ==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UDZiZjNDdFFvOTRQTHFW
            bTQyMTlVcEttdGlwcVVRaE1UaGtaQmU2emh3Ckh0OGtzN1A4Y2JkUTJCaHJKeVpm
            VVAva0ZLV2lLeUs2eVZHbWVpZkJISGsKLS0tIE9FTXlLNXJZWTBzd3ljeUpaMm5M
            eERoRVFHalFETzlQTDkvS0NuLy9oejQKdW/TE1cRFYSCHnogEq8E7jp9MzymcjIx
            5xGFBw1q4Aqr31/BenVHhvFMQntpiFKy8n+69vAG8tCkexNsddczgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T03:37:43Z"
    mac: ENC[AES256_GCM,data:lITY+b2nQShjXzRLDq9WjL46BC/tEsuOPKIaKh/Q9FqHkdnK2xWNEU7yW0uypUnAn7tVBBEdm82T3VPwWhdwdDW/yO5wHoKzrfxCNxpEkLH4DR7QPZ0+3K542Q/VjWT0NyOo6O+HQsy03w4ugc+aAo01nKDe7ubEqBe+QEdFFu8=,iv:AIiwYIw91LYrwfnnABJOIXyOZBTxMiRsclIqIazrEhc=,tag:x6obspt3UGTSfdETlBbNbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
