apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:sRHHHR+G7rj4JZwpBAGe01A=,iv:P9gtk8EbNldQ5xcwe7vEORT97evzK6vU7UmMB8xCHaA=,tag:3r6+uaEKSHMaAatnv87/AQ==,type:str]
    client_secret: ENC[AES256_GCM,data:Wpz7AHiHvASqt1KBlsZkAlzb/PTTcGXG4PjaBmplNs6Yu87h9QI38zVjJdF6NJsooaXzWrj8UCDIupTUYRRl,iv:ceKL4ruq1erLh3YMBDG62dlm0rFfuFcfnLiq3ehASf0=,tag:6gAYPMpGo5mMqivoERufww==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckVQSGRDc3pvdHg3UHVu
            dC8vc0dtV0hKU29jTnJUYUhDMndSRWNSb0J3ClpST0VZQkVDNDJGa3RxT2R3Ynlo
            cjF0ZytMV1dQNWc1Zm13VzY4RjlZMGcKLS0tIFM1Zk5UOFJWOXJZY0ZIZGRMRlVT
            eVQzalBrU255RzdERGFkdXZJU0JnYjgKgS04M/hCQWzc7UBNC61XJeGMsX401s7J
            V+x0KkpNDc/70lRn+HFK2wpfcwXKs23qARecI7yZKuDajMwiWTM43Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T09:32:59Z"
    mac: ENC[AES256_GCM,data:kxaNcFYMSIVeGqrvzGPPTVp8PPwiEWMBHizSvRyKN58v/MrbTd+ddS/yAS6zdinMPVoxkegBWghn8AF8dxKRr2nMTuyTwczZsatpKVL3xrCXz/u3X/WB6JbrJfTuwhpKRJuM0CNY8YBPmlV3/5dz0D7+DSceMVXc/kqHMbXxNGQ=,iv:2KKswUj8v63yUntiDCKvitQ64OWVwH1wEi3ExaQJ+40=,tag:Nny/mp70q5nbfgZ0V9MzGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
