apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:sRHHHR+G7rj4JZwpBAGe01A=,iv:P9gtk8EbNldQ5xcwe7vEORT97evzK6vU7UmMB8xCHaA=,tag:3r6+uaEKSHMaAatnv87/AQ==,type:str]
    client_secret: ENC[AES256_GCM,data:Wpz7AHiHvASqt1KBlsZkAlzb/PTTcGXG4PjaBmplNs6Yu87h9QI38zVjJdF6NJsooaXzWrj8UCDIupTUYRRl,iv:ceKL4ruq1erLh3YMBDG62dlm0rFfuFcfnLiq3ehASf0=,tag:6gAYPMpGo5mMqivoERufww==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckVQSGRDc3pvdHg3UHVu
            dC8vc0dtV0hKU29jTnJUYUhDMndSRWNSb0J3ClpST0VZQkVDNDJGa3RxT2R3Ynlo
            cjF0ZytMV1dQNWc1Zm13VzY4RjlZMGcKLS0tIFM1Zk5UOFJWOXJZY0ZIZGRMRlVT
            eVQzalBrU255RzdERGFkdXZJU0JnYjgKgS04M/hCQWzc7UBNC61XJeGMsX401s7J
            V+x0KkpNDc/70lRn+HFK2wpfcwXKs23qARecI7yZKuDajMwiWTM43Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T09:50:22Z"
    mac: ENC[AES256_GCM,data:kbSl1Ta3MgntUJyPkw3Td6r6ZNu3N9op2lwYrxVpoWHy9ryU4UIYIugqsf7hCGh6kv7UQFOlDY6CW5qazf9ET57r2eWLdCr8rbE4b3OBgcdSDxouLmwf5KMLjlZPJfro8knjsi3jq5PfvyBzEPFn9cAQlVColGlbtUSxo8x7pBg=,iv:xLGeP2LXk0wjb+zmJc5sR5KSptQwYoPbe4XyMK5s75o=,tag:zOaDkEq7QsDjKzVPyCkRog==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
