---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: atlas-nl.rya-tone.ts.net
  name: atlas-nl
spec:
  externalName: placeholder
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: atlas-ru.rya-tone.ts.net
  name: atlas-ru
spec:
  externalName: placeholder
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: keenetic-fm.rya-tone.ts.net
  name: keenetic-fm
spec:
  externalName: placeholder
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: keenetic-hm.rya-tone.ts.net
  name: keenetic-hm
spec:
  externalName: placeholder
  type: ExternalName
