---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria-metrics-agent
  namespace: observability
spec:
  replicaCount: 1
  # Select all scrape objects in the cluster
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vminsert-victoria-metrics-cluster.observability.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
