---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: victoria-metrics-cluster
  namespace: observability
spec:
  retentionPeriod: "1y"
  replicationFactor: 2
  vmstorage:
    replicaCount: 3
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: openebs-hostpath
  vmselect:
    replicaCount: 2
    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: openebs-hostpath
  vminsert:
    replicaCount: 2
