apiVersion: v1
kind: Secret
metadata:
  name: github-status-token-secret
stringData:
  token: ENC[AES256_GCM,data:8fUvbT3H69jN6Jtz64jwOInakKPWlhiBIbQ1dV9AWqKUgo9kaxPhCfQb7iOwViCbRizdo94SJjJybpPZ/ymCEQAKJW6DAdSScswv4cIgnD/lqqc7YtB6fFBysEzN,iv:VAYrVRkxbA76woiu0hjTDIGs31x71sve6xLspXBNY8w=,tag:z16rjM4JyBMQULXxFdKdDQ==,type:str]
sops:
  age:
    - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRlBFTWhYekl6ZGQxSFAw
        Ynk1NVlQWjllVmJhanBIZGFRRTlGN25Jdm5nCkpXVFM5b3RuWkZVcXVNZXh3d0Q4
        NnF6TDVQdmdLTGp3dERkOWp5V3hJS1kKLS0tIFlDYlp2LzRNQzh2bGRodm42dWxJ
        ODRqa0x5WC9xRGJMbHZ1bFdEZlBjalEKvjLNd/2VZB9tMB9ExeEWEBbQQDUmCLGs
        tbTaz/c+WzvtgSOoeEoHytmemCybA2ELN/TWNH1RsB9TVpzOnJ8XuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-07T15:45:34Z"
  mac: ENC[AES256_GCM,data:0bs3y4dJV8o/+ub2lFtvvG/wQ5Q+vKsZcW1cWTpOhAN+UWm/jhCAi75zFL+XNIKOHmwI1kZ3IwAz3D9mUi6Krjeqw9GtFgeDwjotzn97YVcJOn9NuBZhBW2QmVpw2jutwJDKa4WOiVk950P9hnYFbqePG2s02PXMMCGWtkDLqeo=,iv:FPpLkjs6ZmM97DdqBI0FIItZU0r3kL7PXe+gJmm/dbw=,tag:Vg7BuvlRHqkjY9DWnoS4rA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
