# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-secret
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:6u+Dj/ZgCtWpmMXDAoOczHaowKnoTgO0Nhe69RV2DmtPkR7q0BxDn9sKTREnqtUktCd2EA7S7X7DA5na/qC9hYXXyzAHU05Sdg==,iv:HMOEoac2EXqMloVsccOug9ROzqXkNw0RixZO7gL5sSI=,tag:M7vjaSU7lmE41MY7Xeuwmw==,type:str]
    ZEROCLAW_DBNAME: ENC[AES256_GCM,data:9DZ3ZwfvUgM=,iv:2KMS0F9TzsNePVfHZHDkVKOTYGYfd3BUjvqT5LKMrsU=,tag:KcbTPDRgAaP72Dro07kzEw==,type:str]
    ZEROCLAW_DB_USER: ENC[AES256_GCM,data:EsGAY0IQLKg=,iv:cdkWuzar7GXSQYeVj1FbdX+CCVLBxGiTqS63EgtW2xk=,tag:mNMOdKrE2fNsBDAZcb889Q==,type:str]
    ZEROCLAW_DB_PASS: ENC[AES256_GCM,data:iGfXVmZ2rkSDNcRm,iv:id6lz10QetuNnVmbXeA/esE/nNtOdmKMyp9OWnPOrDA=,tag:AFUI2IzVVpS5kS2OnOAUaw==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU2RML2hxaEVCZEUrWDlV
            TndjK2tvL0Y2V3J4R3VpSWpUQVNuVEpSOW4wCmNBMEhYSDcyTkxSUkJwSnZiL1d6
            VzlSQmNYbDVaMmNkcWxrbXBDYWx4cHMKLS0tIEVPUEJIUysxTVAvVHVRODEvd3h0
            QUN5VldseEVwcjBiamRaRU4vRVcycW8KQOwvr3O6ItITNJpotL2WhHVju8wY/pjO
            aufmRGGUgw9lr2PiauwiW4vfDNFuxMCJRmQjlzYC5cg7Rt7D5tyghQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T06:16:43Z"
    mac: ENC[AES256_GCM,data:C1GNu4TOYOdHhOhwS8TUHfTYKJrVq7wDZrcJ5+hIC3LLunGdY5MJGxIvqLqDiq11d6RRqfRjjUTUX/YGzgCMvvDr5SmlPgECQAu4WktBbHuibu+LcIuWd7MQI3W5kiiRsRvyVWQD2xnJmBeFa7vaMKpxjGbBAdXHYcXTf7BtVlY=,iv:ViD8WDZ1rfTRJh7bw16EDM6NRL9kznK1OlP8le68o2Y=,tag:TYvSRpRcDOMy8AWAbWs+JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
