# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: zeroclaw-secret
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:jL2ynD2r6t8SuHg5Vw+EoJxAIAk9hL4Fw3Gm+OiOw2eEQePMBQMH2iWkayB02Ggka0QwXdGjt4S5uedhI89e1skQ68t44GO9fA==,iv:b4+a30VP6fDgI4eTSsw5EuRWraIUeJpCWW4Dy6+UvEE=,tag:eZwiHTNLStaVfF/AhxoKAg==,type:str]
    ZEROCLAW_DBNAME: ENC[AES256_GCM,data:N3oa2QxuIKo=,iv:s/4D6kfVpOrIBFJuRJJaXw7m6rZX8LZwuszsKCUo98w=,tag:Qw+rrf2M1hp/n7MJP7eBow==,type:str]
    ZEROCLAW_DB_USER: ENC[AES256_GCM,data:bRCr/XETlcE=,iv:+mqWTT0k0DRDXehhHBO+MZ+bxR1LteuKR727hDJBEno=,tag:rpNQYFrR4tZQziCpfO7vYQ==,type:str]
    ZEROCLAW_DB_PASS: ENC[AES256_GCM,data:rxKyqGAaQOp/tEY3,iv:6244AZRYhHfdvhiZZIZy6h1RQPsb8xQKQtsbjyGYQDI=,tag:WZ6NFh65+gU6fQ4p4mNP7A==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:IYlYvHyjbG+S583Bu2CXoT0B7MtAiZ5auQ5NjdeA,iv:gXqE7uercy1WaUPEHA7xiMNtuOa54DJRkGAGIMhsyX8=,tag:GYjAGKbiAQZudw3MxoqHfw==,type:str]
    .env: ENC[AES256_GCM,data:yi82W1lnLJzv3wAXSvCR/f5zKbKngGeu5Ngz37jCyRuZLElckHtGH0F1ZHLzVkDM4Gd7yBigiTBsQu5y+EMh06QMrk+DeX0FIB2fJGNjZV78HsXO3A==,iv:/M3EdY25szWfKjvPVj5T1W7ZLuviR/kkU7PfPm5YVCs=,tag:slVO9RVA16/7Eb4RBYlDAQ==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd3c4WUpBd1NQWlpmRnEr
            cGNmdzE2NFF2ZGZ0VnNiM2hBcy9GanA5OTJvClZXb2EwTTB5RFNSL3pVcTNlcXN0
            cGJtVVZWMUx1bzIvWmhuRzE0blNua3cKLS0tIHplV1ZiNEdKTnFoNUtrV3JuVFJR
            bGVQTVBRc1grckpKdEVhYlBXNjdnZjAKVgaPcPw3ePBzp4VTDFNrw323ztmrc/ic
            m6uPvSWizUagv8OaMKNT9qgr6JJvrf3UDZT02cMEUFkiath70OoonA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T08:05:06Z"
    mac: ENC[AES256_GCM,data:yLrPX5XVCTnDtZQGQB0wN7r0bqGiab98xOQue3Q4k1+2jyKnY/iC+cZL2ty13a6bS+38/T04JNpEQ9QW1XpZoNUTb5zY5wfq2kLoJHGBT0Gix3JDkdYRazNviKDDcf7ooyQo2mbug9TXP0leeAisOoE/J3fGMLtZbKwEZYTs8UQ=,iv:2O4cziiq5JmcqygFoJ97hVIU/mvgLv/y4FXTRytpbE0=,tag:m4RLqNALGIjkKZO5JVYcHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
