apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUSHOVER_ALERTMANAGER_TOKEN: ENC[AES256_GCM,data:mNoq/4nEwSFKi6C5L2/uHKKglYQzb4HCE/sVV+U3,iv:fIItihofObCHDvZfcEeYqlt0dPeYEgdDjY4IHAhMrC4=,tag:dLD/VPTQoSl0/nFfBakOfA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Y+h26di4IGFoqG8yMF/Z2r31DryxUgVp3FXyq3pP,iv:6BqDnaj8r5VIrqf4mvMR19/0NKVSBxl+ZSbB4czZ/Eg=,tag:/benCuItWW14R+sdh5Y4pg==,type:str]
    KURED_NOTIFY_URL: ENC[AES256_GCM,data:48UkJIhjVtJrGCIVm4UWxGRjggqrXw6rsvbH/9743NBTJ7BWA4NDTwDarty+0HpnQAA6j6jFtOaFrRlU81BDfZ0Q0kN5R21mV2OR8QUCm8zC,iv:9SslxYe3oKQxdg4psj977Sl217T/edhHnPEkhWzGZsM=,tag:HJkcc7U+3a6qOTOelXQkig==,type:str]
    ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:DdtGurVHJRpUHyeOCDDnpLC9TIzUQKNNsdU8uzPsHYa2OwcH/j337Vd9eaX7M/B+zYTFEmWMb7RzYuhc9Ls97hA5UVjoPNmWVNkICuqMBb5rPid5Ow==,iv:Mh1djsOVPjNQcP0wbDm+WgnDXaA2SZxAMQbDk0/VG34=,tag:fgj4FuEqLEpobzBI1nnDow==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:uIQDuqPCyXI=,iv:1pJ092dHg5q3xGTXvjwNjqScf3SwPs/0kURT/wwAupQ=,tag:pqSO84HZVdjzAkIuJZMlVQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3NKoe+d914ejIukZFAz17g==,iv:DQ5X2n3Rou0CVzLP98acW0XDBKGS3ATAqWKlVYh9zlU=,tag:xK9jsWfIWkZn190pFBgUCg==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL2lnK1U0dCticDlSWVZm
            N3NGenBhS3JuLzU5YTJLWnFIY1N4RUthMkhrCit4QmhKSHgvaExnSzZhQUxXQndO
            RU5nLzNNSW9ZMmxyV3BaQ2I1a2IzazgKLS0tIEwwUEI2V3V5ZWlMUG5UdTFkTTlT
            Skp0aUVndEVxekxqV2tDbTI4SU4vWjQKDqSVjGNLLFMOHnbGzCSzAwG3mDPujWTs
            BwbCVMiELQFyedCH93RC0ftjhvmZUL4ce70bUiphAourouuHwUnh3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:26:20Z"
    mac: ENC[AES256_GCM,data:t0PlNiW20HbB0sQLheh20u6AO4mpM13GBaErT+D4SnDq5zfoTrJWPWioyzvIfUey+lXb+q+VnRlT2GCiFjIWUr747+4q0W5WEj/FFBtSyYgDc1iVPxVDd1bVjoKT4G2K7R8wphmIy+uiHxteX+eSRNOfINAnU5txh9DUTRWTvjs=,iv:AiORB82Pi4j3yVvCHmoW0bcXqCVpd+oXFOh7YN6j52s=,tag:8s9ZvTQC1PXorSQCT6NNlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
