apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:r4OQN8im1BYe,iv:gZ3FTiarBLmjbgz9wOe6TTizQbkPXdENrONZs2vUsF4=,tag:SVossd3n5OrRwZtlqgCtVA==,type:str]
    PUSHOVER_ALERTMANAGER_TOKEN: ENC[AES256_GCM,data:mNoq/4nEwSFKi6C5L2/uHKKglYQzb4HCE/sVV+U3,iv:fIItihofObCHDvZfcEeYqlt0dPeYEgdDjY4IHAhMrC4=,tag:dLD/VPTQoSl0/nFfBakOfA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Y+h26di4IGFoqG8yMF/Z2r31DryxUgVp3FXyq3pP,iv:6BqDnaj8r5VIrqf4mvMR19/0NKVSBxl+ZSbB4czZ/Eg=,tag:/benCuItWW14R+sdh5Y4pg==,type:str]
    KURED_NOTIFY_URL: ENC[AES256_GCM,data:48UkJIhjVtJrGCIVm4UWxGRjggqrXw6rsvbH/9743NBTJ7BWA4NDTwDarty+0HpnQAA6j6jFtOaFrRlU81BDfZ0Q0kN5R21mV2OR8QUCm8zC,iv:9SslxYe3oKQxdg4psj977Sl217T/edhHnPEkhWzGZsM=,tag:HJkcc7U+3a6qOTOelXQkig==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL2lnK1U0dCticDlSWVZm
            N3NGenBhS3JuLzU5YTJLWnFIY1N4RUthMkhrCit4QmhKSHgvaExnSzZhQUxXQndO
            RU5nLzNNSW9ZMmxyV3BaQ2I1a2IzazgKLS0tIEwwUEI2V3V5ZWlMUG5UdTFkTTlT
            Skp0aUVndEVxekxqV2tDbTI4SU4vWjQKDqSVjGNLLFMOHnbGzCSzAwG3mDPujWTs
            BwbCVMiELQFyedCH93RC0ftjhvmZUL4ce70bUiphAourouuHwUnh3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T20:03:19Z"
    mac: ENC[AES256_GCM,data:H15X9DyT8B8zaLcCZPEOdBCneJx3A++wJc3/O1JZM1f8sttWcIKUKjWsZDaBM8PVJwMNRDMRiqiMGbe3VY1of31xxny75Dn3H9qPz0gsnbxH02IECLlPsfkErFyjsR6Uq8swDpT2tLasc7V8cqBs/d/H/Q0nGuKq3yZAanx2dZQ=,iv:cVKUQVpJnf4/0v/z5O6wbObExowFRKY0u5a1wqjxPj4=,tag:C7fL1Pts9m6/15rLpoZiTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
