apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:VedxFba05MYLEmWg0J6OZ6qJOzuiZF4Vu46n5OVweJnZYqDXn3jLy6yOKN+vSen9pUpJMtN3l9tGUWEwbs1j8ZNRQ2FsCuQJZrQ=,iv:VZXEDL//wcx6z17+sEs4k11An+kt3WEpjbYrYXO+wcA=,tag:oQYcsj7tVkT+hln2x7e97w==,type:str]
sops:
  age:
    - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmxuSCtEdFg2TkJVUVJO
        b3lwUEQ2MTgrRWs0eHZJbDAzMzE3TjhRUmtzCjRKbGFsaGsvUTlER1VnTDhHKzlE
        UWVmYzBBbjZ6c0lsNTBSaVVrL0l4RmsKLS0tIGlpeGVZU0JhOVA4R2hOYXVXenJQ
        WWJPMXdieS9USFplVFB3WldZT3VGajQK4bftmttY9UGx0oq54Qmctf4apQdSQqy0
        eSd2FSNflHDuGQq9tXY4Y2D4/7V96C61fsDHHxfRsDjIIMPCPaf63w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-22T07:55:12Z"
  mac: ENC[AES256_GCM,data:Qw/XvPvhYGAcPanYGsKgTsYAHobZPsaVor+zDHTePczq81StkP69JIT67nCuXstEf84cxdUi5OqyLH/spmECz5Soyt5wZqfZ13mAwQW7Wp5eQ8tcfaY28vgj7EwiHmypqRz/jReG+quoy4FTENv/PUzvcyjCHVI9fVff1533hck=,iv:lh7a3VvtQ5bfsQCvZL674n8G3tUQwrNsyKZLiO4Lyo0=,tag:8we39wXi0ea6M/hApSbnMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
